spring.rabbitmq.host=34.27.49.118
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

fileupload.rabbitmq.queue=file-queue
fileupload.rabbitmq.exchange=file-queue.exchange
fileupload.rabbitmq.routing=file-queue.routing

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB



spring.main.allow-bean-definition-overriding=true